### ISSUE TITLE
ros+docker中vscode的问题

### ISSUE THREAD

**Issue by haohaoalt** [fishros/install#14]
一键安装docker + ros 中提供了vscode安装选择，但安装完成后似乎并不可用（也许是我的问题，因为我用的是nano的18.04）
总结下来： docker + ros 中可以roscore，但一些基础的工具并没有具备，甚至vim都没有；想问一下后续可不可以在docke中加入基本的操作工具及编译工具？

**Comment by fishros** [comment]
考虑到镜像体积问题就用了比较干净的镜像,不同人需求不同,后续可提供使用自己镜像的接口
