### ISSUE TITLE
.bashrc 建议检测用户； rosdep 仍需要 githubusercontent

### ISSUE THREAD

**Issue by e71828** [fishros/install#15]
人生苦短，我用 python

大善人属实。

```
RUN Choose Task:[请输入括号内的数字]
---众多工具，等君来用---
[1]:一键安装:ROS(支持ROS和ROS2,树莓派Jetson)
[
11]:一键安装:ROS+Docker(支持所有版本ROS/ROS2)
[2]:一键安装:github桌面版(小鱼常用的github客户端)
[3]:一键配置:rosdep(小鱼的rosdepc,又快又好用)
[4]:一键配置:ROS环境(快速更新ROS环境设置,自动生成环境选择)
[5]:一键配置:系统源(更换系统源,支持全版本Ubuntu系统)
[6]:一键安装:nodejs
[7]:一键安装:VsCode开发工具
[8]:一键安装:Docker
[9]:一键安装:Cartographer(内测版v0.1)
[10]:一键安装:微信(可以在Linux上使用的微信)
[77]:测试模式:运行自定义工具测试
[0]:quit
请输入[]内的数字以选择:请输入[]内的数字以选择:4
/tmp/fishinstall/tools/tool_config_rosenv.py: No such file or directory
欢迎使用一键配置ROS开发环境,本工具由作者小鱼提供
Run CMD Task:[ls /opt/ros/*/setup.bash]
[-]Result:success

Run CMD Task:[ls /home/*/.bashrc]
[-]Result:success

检测到系统有1个ROS环境,已为你生成启动选择,修改~/.bashrc可关闭
欢迎加入机器人学习交流QQ群：139707339(入群口令：一键安装)
如在使用过程中遇到问题，请打开：https://fishros.org.cn/forum 进行反馈
root@VITASOY:~/install#
```

**Comment by e71828** [comment]
我 ×，已经在 root 了，但你添加到 home 里了。

**Comment by e71828** [comment]
好吧，看了你的源码。你都检测了。

然而，wsl 中已经添加了一个普通用户，但是登录的时候自动为 root。

我还要搜搜怎么自动以普通用户登录。傻啦吧唧。

**Comment by e71828** [comment]
你的rosdep 不太行。

参考一下 [rosdep](https://mirrors.tuna.tsinghua.edu.cn/help/rosdistro/)


失败了两次，不同的地方。

```bash
root@VITASOY:~/install# rosdep update
reading in sources list data from /etc/ros/rosdep/sources.list.d
Warning: running 'rosdep update' as root is not recommended.
  You should run 'sudo rosdep fix-permissions' and invoke 'rosdep update' again without sudo.
Hit https://mirrors.tuna.tsinghua.edu.cn/github-raw/ros/rosdistro/master/rosdep/osx-homebrew.yaml
Hit https://mirrors.tuna.tsinghua.edu.cn/github-raw/ros/rosdistro/master/rosdep/base.yaml
Hit https://mirrors.tuna.tsinghua.edu.cn/github-raw/ros/rosdistro/master/rosdep/python.yaml
Hit https://mirrors.tuna.tsinghua.edu.cn/github-raw/ros/rosdistro/master/rosdep/ruby.yaml
Query rosdistro index https://raw.githubusercontent.com/ros/rosdistro/master/index-v4.yaml
Skip end-of-life distro "ardent"
Skip end-of-life distro "bouncy"
Skip end-of-life distro "crystal"
Skip end-of-life distro "dashing"
Skip end-of-life distro "eloquent"
Add distro "foxy"
Add distro "galactic"
ERROR: error loading sources list:
        The read operation timed out (https://raw.githubusercontent.com/ros/rosdistro/master/galactic/distribution.yaml)
root@VITASOY:~/install#
root@VITASOY:~/install#
root@VITASOY:~/install# sudo rosdep fix-permissions
Recursively changing ownership of ros home directory '/root/.ros' to 'root:root' (current user)...
Done.
root@VITASOY:~/install# rosdep update
reading in sources list data from /etc/ros/rosdep/sources.list.d
Warning: running 'rosdep update' as root is not recommended.
  You should run 'sudo rosdep fix-permissions' and invoke 'rosdep update' again without sudo.
Hit https://mirrors.tuna.tsinghua.edu.cn/github-raw/ros/rosdistro/master/rosdep/osx-homebrew.yaml
Hit https://mirrors.tuna.tsinghua.edu.cn/github-raw/ros/rosdistro/master/rosdep/base.yaml
Hit https://mirrors.tuna.tsinghua.edu.cn/github-raw/ros/rosdistro/master/rosdep/python.yaml
Hit https://mirrors.tuna.tsinghua.edu.cn/github-raw/ros/rosdistro/master/rosdep/ruby.yaml
Query rosdistro index https://raw.githubusercontent.com/ros/rosdistro/master/index-v4.yaml
Skip end-of-life distro "ardent"
Skip end-of-life distro "bouncy"
Skip end-of-life distro "crystal"
Skip end-of-life distro "dashing"
Skip end-of-life distro "eloquent"
Add distro "foxy"
Add distro "galactic"
Skip end-of-life distro "groovy"
Add distro "humble"
Skip end-of-life distro "hydro"
Skip end-of-life distro "indigo"
Skip end-of-life distro "jade"
Skip end-of-life distro "kinetic"
Skip end-of-life distro "lunar"
Add distro "melodic"
ERROR: error loading sources list:
        The read operation timed out (https://raw.githubusercontent.com/ros/rosdistro/master/melodic/distribution.yaml)
root@VITASOY:~/install#
```

**Comment by e71828** [comment]
```
CmdTask("export ROSDISTRO_INDEX_URL=https://mirrors.tuna.tsinghua.edu.cn/rosdistro/index-v4.yaml", 0).run()
```


```bash
ERROR: error loading sources list:
        The read operation timed out (https://raw.githubusercontent.com/ros/rosdistro/master/galactic/distribution.yaml)
root@VITASOY:~# echo $ROSDISTRO_INDEX_URL

root@VITASOY:~# echo $ROSDISTRO_INDEX_URL

root@VITASOY:~#

```

变量会消失。

**Comment by fishros** [comment]
> 你的rosdep 不太行。
> 
> 参考一下 [rosdep](https://mirrors.tuna.tsinghua.edu.cn/help/rosdistro/)
> 
> 失败了两次，不同的地方。
> 
> ```shell
> root@VITASOY:~/install# rosdep update
> reading in sources list data from /etc/ros/rosdep/sources.list.d
> Warning: running 'rosdep update' as root is not recommended.
>   You should run 'sudo rosdep fix-permissions' and invoke 'rosdep update' again without sudo.
> Hit https://mirrors.tuna.tsinghua.edu.cn/github-raw/ros/rosdistro/master/rosdep/osx-homebrew.yaml
> Hit https://mirrors.tuna.tsinghua.edu.cn/github-raw/ros/rosdistro/master/rosdep/base.yaml
> Hit https://mirrors.tuna.tsinghua.edu.cn/github-raw/ros/rosdistro/master/rosdep/python.yaml
> Hit https://mirrors.tuna.tsinghua.edu.cn/github-raw/ros/rosdistro/master/rosdep/ruby.yaml
> Query rosdistro index https://raw.githubusercontent.com/ros/rosdistro/master/index-v4.yaml
> Skip end-of-life distro "ardent"
> Skip end-of-life distro "bouncy"
> Skip end-of-life distro "crystal"
> Skip end-of-life distro "dashing"
> Skip end-of-life distro "eloquent"
> Add distro "foxy"
> Add distro "galactic"
> ERROR: error loading sources list:
>         The read operation timed out (https://raw.githubusercontent.com/ros/rosdistro/master/galactic/distribution.yaml)
> root@VITASOY:~/install#
> root@VITASOY:~/install#
> root@VITASOY:~/install# sudo rosdep fix-permissions
> Recursively changing ownership of ros home directory '/root/.ros' to 'root:root' (current user)...
> Done.
> root@VITASOY:~/install# rosdep update
> reading in sources list data from /etc/ros/rosdep/sources.list.d
> Warning: running 'rosdep update' as root is not recommended.
>   You should run 'sudo rosdep fix-permissions' and invoke 'rosdep update' again without sudo.
> Hit https://mirrors.tuna.tsinghua.edu.cn/github-raw/ros/rosdistro/master/rosdep/osx-homebrew.yaml
> Hit https://mirrors.tuna.tsinghua.edu.cn/github-raw/ros/rosdistro/master/rosdep/base.yaml
> Hit https://mirrors.tuna.tsinghua.edu.cn/github-raw/ros/rosdistro/master/rosdep/python.yaml
> Hit https://mirrors.tuna.tsinghua.edu.cn/github-raw/ros/rosdistro/master/rosdep/ruby.yaml
> Query rosdistro index https://raw.githubusercontent.com/ros/rosdistro/master/index-v4.yaml
> Skip end-of-life distro "ardent"
> Skip end-of-life distro "bouncy"
> Skip end-of-life distro "crystal"
> Skip end-of-life distro "dashing"
> Skip end-of-life distro "eloquent"
> Add distro "foxy"
> Add distro "galactic"
> Skip end-of-life distro "groovy"
> Add distro "humble"
> Skip end-of-life distro "hydro"
> Skip end-of-life distro "indigo"
> Skip end-of-life distro "jade"
> Skip end-of-life distro "kinetic"
> Skip end-of-life distro "lunar"
> Add distro "melodic"
> ERROR: error loading sources list:
>         The read operation timed out (https://raw.githubusercontent.com/ros/rosdistro/master/melodic/distribution.yaml)
> root@VITASOY:~/install#
> ```

这里要用rosdepc update,而不是rosdep update

**Comment by fishros** [comment]
> 好吧，看了你的源码。你都检测了。
> 
> 然而，wsl 中已经添加了一个普通用户，但是登录的时候自动为 root。
> 
> 我还要搜搜怎么自动以普通用户登录。傻啦吧唧。
> 
> **建议检测 $USER，搜索太暴力。**

直接使用一键安装ros,会配置好环境,user也有查,有的时候会多,所以用了多种方法
