### ISSUE TITLE
关于Ubuntu18.04桌面版安装微信后不能使用的问题

### ISSUE THREAD

**Issue by Cyz981126** [fishros/install#16]
小鱼，你好，
         我使用了你开发的，一行命令安装“linux可用的微信”后，在应用程序中出现了微信的图标，但是在我点击该图标后，没有响应，无事发生。
         另外，我还使用了一行命令安装“ROS”和“VSCode”，均安装成功，非常好用，是对初学者入门和机器人社区很具有价值的贡献，谢谢你。
         我使用的平台是，Ubuntu18.04桌面版。

**Comment by fishros** [comment]
> 小鱼，你好， 我使用了你开发的，一行命令安装“linux可用的微信”后，在应用程序中出现了微信的图标，但是在我点击该图标后，没有响应，无事发生。 另外，我还使用了一行命令安装“ROS”和“VSCode”，均安装成功，非常好用，是对初学者入门和机器人社区很具有价值的贡献，谢谢你。 我使用的平台是，Ubuntu18.04桌面版。

尽量使用docker版本，桌面版对环境要求不一致容易出现依赖错误，后续会更新轻量的docker版本。
