### ISSUE TITLE
调用ROS官方ros_cross_compile时使用rosdepc错误

### ISSUE THREAD

**Issue by BraveClient** [fishros/install#17]
具体错误如下，看了一下是因为打印了中文的原因。
所以希望要脚本前加UTF8的支持，或去掉中文。
INFO:Docker Client:Traceback (most recent call last):
  File "/usr/local/bin/rosdepc", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/rosdepc/rosdepc.py", line 8, in main
    print('\u6b22\u8fce\u4f7f\u7528\u56fd\u5185\u7248rosdep\u4e4brosdepc\uff0c\u6211\u662f\u4f5c\u8005\u5c0f\u9c7c\uff01\n')
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-6: ordinal not in range(128)

**Comment by fishros** [comment]
问题已解决,可以直接修改rosdepc源码
