### ISSUE TITLE
请教 docker pull 的问题

### ISSUE THREAD

**Issue by jabobian** [fishros/install#20]
我之前用Docker Desktop，默认都是使用user权限，同时在终端也直接用 docker 命令，不加 sudo。
但是使用 鱼香ROS 一键安装 ROS+Docker，发现里面都是使用 sudo docker * 指令，所以下载的 image 只有在 sudo docker 指令下才能看到。

现在的问题是，我测试了一下不用 sudo，竟然不能 pull，请问有什么办法。感谢！

···
rosfun@rosfun-pc:~$ docker pull fishros2/ros:humble-desktop-full
Error response from daemon: Head "https://registry-1.docker.io/v2/fishros2/ros/manifests/humble-desktop-full": EOF

rosfun@rosfun-pc:~$ sudo docker pull fishros2/ros:humble-desktop-full
[sudo] password for rosfun: 
humble-desktop-full: Pulling from fishros2/ros
Digest: sha256:c82cab48915f57844d92c0dbbbb5de881f3eaa2297ceb77c87b9531ab92493a5
Status: Image is up to date for fishros2/ros:humble-desktop-full
docker.io/fishros2/ros:humble-desktop-full
···

**Comment by jabobian** [comment]
其实我觉得好奇的是，为什么一定要用 sudo docker pull 呢

**Comment by fishros** [comment]
默认用户没有docker权限，无法获取到sock，所以需要sudo，要想不加需要添加组，再一键安装代码里有
