### ISSUE TITLE
wget 一键安装失败：.: no such file or directory: fishros

### ISSUE THREAD

**Issue by yulinlina** [fishros/install#22]
ubuntu 版本22.04
zsh终端
## 终端内容

--2023-02-26 16:54:33-- http://fishros.com/install
Resolving [fishros.com](http://fishros.com/) ([fishros.com](http://fishros.com/))... 139.9.131.171
Connecting to [fishros.com](http://fishros.com/) ([fishros.com](http://fishros.com/))|139.9.131.171|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: http://fishros.com/install/ [following]
--2023-02-26 16:54:33-- http://fishros.com/install/
Reusing existing connection to [fishros.com:80](http://fishros.com/).
HTTP request sent, awaiting response... 200 OK
Length: 582 [application/octet-stream]
Saving to: ‘fishros’

fishros 100%[======================================================================================================================================================================>] 582 --.-KB/s in 0s

2023-02-26 16:54:34 (33.5 MB/s) - ‘fishros’ saved [582/582]

.: no such file or directory: fishros
## 问题

Ubuntu的software提醒我更新我就更新了，然后ros2就用不了了，想重新下载就出现了如上问题，该如何解决？

**Comment by fishros** [comment]
切换到bash使用 可以把 `.  fishros`  替换成 `bash fishros`

**Comment by wo-ai-xue-xi** [comment]
请问是不是不能在zsh中使用一键安装命令，我在zsh中使用一键安装也遇到了没有fishros的问题

**Comment by Z-mingyu** [comment]
> 请问是不是不能在zsh中使用一键安装命令，我在zsh中使用一键安装也遇到了没有fishros的问题

把 . 换成zsh即可
