### ISSUE TITLE
是否有humble安装的支持？

### ISSUE THREAD

**Issue by linmeon** [fishros/install#27]
示例教程貌似是用的humble，安装选项中没有看到这个选项。

RUN Choose Task:[请输入括号内的数字]
请选择你要安装的ROS版本名称(请注意ROS1和ROS2区别):
[1]:melodic(ROS1)
[2]:bouncy(ROS2)
[3]:crystal(ROS2)
[4]:dashing(ROS2)
[5]:eloquent(ROS2)
[0]:quit

首先我们要找到这个头文件在哪里，这个头文件是ROS2的客户端库，其地址肯定在ROS2的安装目录下，即/opt/ros/humble/include/rclcpp。

cd /opt/ros/humble/include/rclcpp
ls rclcpp/* | grep rclcpp.h

**Comment by fishros** [comment]
有的，但是humble只在ubuntu22.04上发布，请更换系统

**Comment by linmeon** [comment]
建议使用什么版本的ros 和Ubuntu呢

**Comment by fishros** [comment]
根据个人和实际项目需要，ROS2 推荐 Ubuntu22+Humble
