### ISSUE TITLE
setup脚本调用问题

### ISSUE THREAD

**Issue by fizecoding** [fishros/install#36]
如果使用zsh安装的话，最终添加的环境变量还是会去到bashrc里面，没有自动调用zsh的setup文件,需要手动运行如source /opt/ros/humble/setup.zsh才可以正常使用。

**Comment by ganyuanzhen** [comment]
可以提交一个pr，将变量添加到 ~/.profile 里面

**Comment by Aurora-edu** [comment]
我想要修这个bug

**Comment by ganyuanzhen** [comment]
> 我想要修这个bug

欢迎Pr，写好后在Pr的地方@一下小鱼

**Comment by ganyuanzhen** [comment]
Fixed by https://github.com/fishros/install/pull/70
