### ISSUE TITLE
安装后无法在Terminal中使用`ros2`或`roscore`启动ros系统。

### ISSUE THREAD

**Issue by BonJohnLee** [fishros/install#39]
安装后无法在Terminal中使用`ros2`或`roscore`启动ros系统。
反馈如下
```
bash: /home/leebj/.bashrc: No such file or directory
```
检查了自己home目录，自己在删除之前安装的ros版本的时候已经删除了.bashrc文件，但是在安装的时候提示中有：
```
检测到系统有1个ROS环境,已为你生成启动选择,修改~/.bashrc可关闭
```
我刚接触ros不久，目前推测是需要自行添加并写入一个.bashrc文件，但是我并不知道应该如何编写，也不知道应该这样会不会影响后期的系统稳定性。

请问应该如何解决？

**Comment by fishros** [comment]
建议从其他地方拷贝一个　bashrc 文件到相同目录
