### ISSUE TITLE
你好  提示apt镜像有问题

### ISSUE THREAD

**Issue by goodluck2q** [fishros/install#4]
你的系统当前apt存在问题，请先使用一键换源处理...若无法处理，请将下列错误信息告知小鱼...['Get:1 https://mirrors.ustc.edu.cn/ubuntu focal InRelease [265 kB]', 'Get:2 https://mirrors.ustc.edu.cn/ubuntu focal-updates InRelease [114 kB]', 'Get:3 https://mirrors.ustc.edu.cn/ubuntu focal-backports InRelease [108 kB]', 'Get:4 https://mirrors.ustc.edu.cn/ubuntu focal-security InRelease [114 kB]', 'Get:5 https://mirrors.ustc.edu.cn/ubuntu focal/main amd64 Packages [970 kB]', 'Get:6 https://mirrors.ustc.edu.cn/ubuntu focal/main armhf Packages [934 kB]', 'Get:6 https://mirrors.ustc.edu.cn/ubuntu focal/main armhf Packages [934 kB]', 'Get:6 https://mirrors.ustc.edu.cn/ubuntu focal/main armhf Packages [934 kB]', 'Get:6 https://mirrors.ustc.edu.cn/ubuntu focal/main armhf Packages [934 kB]', 'Get:6 https://mirrors.ustc.edu.cn/ubuntu focal/main armhf Packages [934 kB]', 'Get:6 https://mirrors.ustc.edu.cn/ubuntu focal/main armhf Packages [934 kB]', 'Get:6 https://mirrors.ustc.edu.cn/ubuntu focal/main armhf Packages [934 kB]', 'Get:6 https://mirrors.ustc.edu.cn/ubuntu focal/main armhf Packages [934 kB]', 'Get:6 https://mirrors.ustc.edu.cn/ubuntu focal/main armhf Packages [934 kB]', 'Get:6 https://mirrors.ustc.edu.cn/ubuntu focal/main armhf Packages [934 kB]', 'Get:6 https://mirrors.ustc.edu.cn/ubuntu focal/main armhf Packages [934 kB]', 'Get:6 https://mirrors.ustc.edu.cn/ubuntu focal/main armhf Packages [934 kB]', 'Get:6 https://mirrors.ustc.edu.cn/ubuntu focal/main armhf Packages [934 kB]', 'Get:6 https://mirrors.ustc.edu.cn/ubuntu focal/main armhf Packages [934 kB]', 'Get:6 https://mirrors.ustc.edu.cn/ubuntu focal/main armhf Packages [934 kB]', 'Get:6 https://mirrors.ustc.edu.cn/ubuntu focal/main armhf Packages [934 kB]', 'Get:6 https://mirrors.ustc.edu.cn/ubuntu focal/main armhf Packages [934 kB]', 'Get:6 https://mirrors.ustc.edu.cn/ubuntu focal/main armhf Packages [934 kB]', 'Get:6 https://mirrors.ustc.edu.cn/ubuntu focal/main armhf Packages [934 kB]', 'Get:6 https://mirrors.ustc.edu.cn/ubuntu focal/main armhf Packages [934 kB]', 'Get:6 https://mirrors.ustc.edu.cn/ubuntu focal/main armhf Packages [934 kB]', 'Get:6 https://mirrors.ustc.edu.cn/ubuntu focal/main armhf Packages [934 kB]', 'Get:6 https://mirrors.ustc.edu.cn/ubuntu focal/main armhf Packages [934 kB]', 'Get:6 https://mirrors.ustc.edu.cn/ubuntu focal/main armhf Packages [934 kB]', 'Get:6 https://mirrors.ustc.edu.cn/ubuntu focal/main armhf Packages [934 kB]', 'Get:6 https://mirrors.ustc.edu.cn/ubuntu focal/main armhf Packages [934 kB]', 'Get:6 https://mirrors.ustc.edu.cn/ubuntu focal/main armhf Packages [934 kB]', 'Get:6 https://mirrors.ustc.edu.cn/ubuntu focal/main armhf Packages [934 kB]', 'Get:6 https://mirrors.ustc.edu.cn/ubuntu focal/main armhf Packages [934 kB]', 'Get:6 https://mirrors.ustc.edu.cn/ubuntu focal/main armhf Packages [934 kB]', 'Get:6 https://mirrors.ustc.edu.cn/ubuntu focal/main armhf Packages [934 kB]', 'Get:6 https://mirrors.ustc.edu.cn/ubuntu focal/main armhf Packages [934 kB]', 'Get:6 https://mirrors.ustc.edu.cn/ubuntu focal/main armhf Packages [934 kB]', 'Get:6 https://mirrors.ustc.edu.cn/ubuntu focal/main armhf Packages [934 kB]', 'Get:6 https://mirrors.ustc.edu.cn/ubuntu focal/main armhf Packages [934 kB]', 'Get:6 https://mirrors.ustc.edu.cn/ubuntu focal/main armhf Packages [934 kB]', 'Ign:6 https://mirrors.ustc.edu.cn/ubuntu focal/main armhf Packages', 'Get:43 https://mirrors.ustc.edu.cn/ubuntu focal/restricted armhf Packages [7,044 B]', 'Get:43 https://mirrors.ustc.edu.cn/ubuntu focal/restricted armhf Packages [7,044 B]', 'Get:43 https://mirrors.ustc.edu.cn/ubuntu focal/restricted armhf Packages [7,044 B]', 'Get:43 https://mirrors.ustc.edu.cn/ubuntu focal/restricted armhf Packages [7,044 B]', 'Get:43 https://mirrors.ustc.edu.cn/ubuntu focal/restricted armhf Packages [7,044 B]', 'Ign:43 https://mirrors.ustc.edu.cn/ubuntu focal/restricted armhf Packages', 'Get:49 https://mirrors.ustc.edu.cn/ubuntu focal/universe armhf Packages [8,321 kB]', 'Get:49 https://mirrors.ustc.edu.cn/ubuntu focal/universe armhf Packages [8,321 kB]', 'Get:49 https://mirrors.ustc.edu.cn/ubuntu focal/universe armhf Packages [8,321 kB]', 'Get:49 https://mirrors.ustc.edu.cn/ubuntu focal/universe armhf Packages [8,321 kB]', 'Get:49 https://mirrors.ustc.edu.cn/ubuntu focal/universe armhf Packages [8,321 kB]', 'Get:49 https://mirrors.ustc.edu.cn/ubuntu focal/universe armhf Packages [8,321 kB]', 'Get:49 https://mirrors.ustc.edu.cn/ubuntu focal/universe armhf Packages [8,321 kB]', 'Get:49 https://mirrors.ustc.edu.cn/ubuntu focal/universe armhf Packages [8,321 kB]', 'Get:49 https://mirrors.ustc.edu.cn/ubuntu focal/universe armhf Packages [8,321 kB]', 'Get:49 https://mirrors.ustc.edu.cn/ubuntu focal/universe armhf Packages [8,321 kB]', 'Get:49 https://mirrors.ustc.edu.cn/ubuntu focal/universe armhf Packages [8,321 kB]', 'Get:49 https://mirrors.ustc.edu.cn/ubuntu focal/universe armhf Packages [8,321 kB]', 'Get:49 https://mirrors.ustc.edu.cn/ubuntu focal/universe armhf Packages [8,321 kB]', 'Get:49 https://mirrors.ustc.edu.cn/ubuntu focal/universe armhf Packages [8,321 kB]', 'Get:49 https://mirrors.ustc.edu.cn/ubuntu focal/universe armhf Packages [8,321 kB]', 'Get:49 https://mirrors.ustc.edu.cn/ubuntu focal/universe armhf Packages [8,321 kB]', 'Get:49 https://mirrors.ustc.edu.cn/ubuntu focal/universe armhf Packages [8,321 kB]', 'Get:49 https://mirrors.ustc.edu.cn/ubuntu focal/universe armhf Packages [8,321 kB]', 'Get:49 https://mirrors.ustc.edu.cn/ubuntu focal/universe armhf Packages [8,321 kB]', 'Get:49 https://mirrors.ustc.edu.cn/ubuntu focal/universe armhf Packages [8,321 kB]', 'Get:49 https://mirrors.ustc.edu.cn/ubuntu focal/universe armhf Packages [8,321 kB]', 'Get:49 https://mirrors.ustc.edu.cn/ubuntu focal/universe armhf Packages [8,321 kB]', 'Get:49 https://mirrors.ustc.edu.cn/ubuntu focal/universe armhf Packages [8,321 kB]', 'Get:49 https://mirrors.ustc.edu.cn/ubuntu focal/universe armhf Packages [8,321 kB]', 'Get:49 https://mirrors.ustc.edu.cn/ubuntu focal/universe armhf Packages [8,321 kB]', 'Get:49 https://mirrors.ustc.edu.cn/ubuntu focal/universe armhf Packages [8,321 kB]', 'Get:49 https://mirrors.ustc.edu.cn/ubuntu focal/universe armhf Packages [8,321 kB]', 'Get:49 https://mirrors.ustc.edu.cn/ubuntu focal/universe armhf Packages [8,321 kB]', 'Get:49 https://mirrors.ustc.edu.cn/ubuntu focal/universe armhf Packages [8,321 kB]', 'Get:49 https://mirrors.ustc.edu.cn/ubuntu focal/universe armhf Packages [8,321 kB]', 'Get:49 https://mirrors.ustc.edu.cn/ubuntu focal/universe armhf Packages [8,321 kB]', 'Get:49 https://mirrors.ustc.edu.cn/ubuntu focal/universe armhf Packages [8,321 kB]', 'Ign:49 https://mirrors.ustc.edu.cn/ubuntu focal/universe armhf Packages', 'Get:82 https://mirrors.ustc.edu.cn/ubuntu focal/multiverse armhf Packages [116 kB]', 'Get:82 https://mirrors.ustc.edu.cn/ubuntu focal/multiverse armhf Packages [116 kB]', 'Get:82 https://mirrors.ustc.edu.cn/ubuntu focal/multiverse armhf Packages [116 kB]', 'Get:82 https://mirrors.ustc.edu.cn/ubuntu focal/multiverse armhf Packages [116 kB]', 'Get:82 https://mirrors.ustc.edu.cn/ubuntu focal/multiverse armhf Packages [116 kB]', 'Get:82 https://mirrors.ustc.edu.cn/ubuntu focal/multiverse armhf Packages [116 kB]', 'Get:82 https://mirrors.ustc.edu.cn/ubuntu focal/multiverse armhf Packages [116 kB]', 'Get:82 https://mirrors.ustc.edu.cn/ubuntu focal/multiverse armhf Packages [116 kB]', 'Ign:82 https://mirrors.ustc.edu.cn/ubuntu focal/multiverse armhf Packages', 'Get:91 https://mirrors.ustc.edu.cn/ubuntu focal-updates/main armhf Packages [930 kB]', 'Get:91 https://mirrors.ustc.edu.cn/ubuntu focal-updates/main armhf Packages [930 kB]', 'Get:91 https://mirrors.ustc.edu.cn/ubuntu focal-updates/main armhf Packages [930 kB]', 'Get:91 https://mirrors.ustc.edu.cn/ubuntu focal-updates/main armhf Packages [930 kB]', 'Ign:91 https://mirrors.ustc.edu.cn/ubuntu focal-updates/main armhf Packages', 'Get:96 https://mirrors.ustc.edu.cn/ubuntu focal-updates/restricted armhf Packages [11.4 kB]', 'Get:96 https://mirrors.ustc.edu.cn/ubuntu focal-updates/restricted armhf Packages [11.4 kB]', 'Get:96 https://mirrors.ustc.edu.cn/ubuntu focal-updates/restricted armhf Packages [11.4 kB]', 'Get:96 https://mirrors.ustc.edu.cn/ubuntu focal-updates/restricted armhf Packages [11.4 kB]', 'Get:96 https://mirrors.ustc.edu.cn/ubuntu focal-updates/restricted armhf Packages [11.4 kB]', 'Get:96 https://mirrors.ustc.edu.cn/ubuntu focal-updates/restricted armhf Packages [11.4 kB]', 'Get:96 https://mirrors.ustc.edu.cn/ubuntu focal-updates/restricted armhf Packages [11.4 kB]', 'Get:96 https://mirrors.ustc.edu.cn/ubuntu focal-updates/restricted armhf Packages [11.4 kB]', 'Get:96 https://mirrors.ustc.edu.cn/ubuntu focal-updates/restricted armhf Packages [11.4 kB]', 'Get:96 https://mirrors.ustc.edu.cn/ubuntu focal-updates/restricted armhf Packages [11.4 kB]', 'Ign:96 https://mirrors.ustc.edu.cn/ubuntu focal-updates/restricted armhf Packages', 'Get:107 https://mirrors.ustc.edu.cn/ubuntu focal-updates/universe armhf Packages [745 kB]', 'Get:107 https://mirrors.ustc.edu.cn/ubuntu focal-updates/universe armhf Packages [745 kB]', 'Get:107 https://mirrors.ustc.edu.cn/ubuntu focal-updates/universe armhf Packages [745 kB]', 'Get:107 https://mirrors.ustc.edu.cn/ubuntu focal-updates/universe armhf Packages [745 kB]', 'Get:107 https://mirrors.ustc.edu.cn/ubuntu focal-updates/universe armhf Packages [745 kB]', 'Get:107 https://mirrors.ustc.edu.cn/ubuntu focal-updates/universe armhf Packages [745 kB]', 'Ign:107 https://mirrors.ustc.edu.cn/ubuntu focal-updates/universe armhf Packages', 'Ign:114 https://mirrors.ustc.edu.cn/ubuntu focal-updates/multiverse armhf Packages', 'Ign:115 https://mirrors.ustc.edu.cn/ubuntu focal-backports/main armhf Packages', 'Ign:116 https://mirrors.ustc.edu.cn/ubuntu focal-backports/universe armhf Packages', 'Ign:6 https://mirrors.ustc.edu.cn/ubuntu focal/main armhf Packages', 'Ign:117 https://mirrors.ustc.edu.cn/ubuntu focal-security/main armhf Packages', 'Ign:118 https://mirrors.ustc.edu.cn/ubuntu focal-security/restricted armhf Packages', 'Ign:119 https://mirrors.ustc.edu.cn/ubuntu focal-security/universe armhf Packages', 'Ign:120 https://mirrors.ustc.edu.cn/ubuntu focal-security/multiverse armhf Packages', 'Ign:43 https://mirrors.ustc.edu.cn/ubuntu focal/restricted armhf Packages', 'Ign:49 https://mirrors.ustc.edu.cn/ubuntu focal/universe armhf Packages', 'Ign:82 https://mirrors.ustc.edu.cn/ubuntu focal/multiverse armhf Packages', 'Ign:91 https://mirrors.ustc.edu.cn/ubuntu focal-updates/main armhf Packages', 'Ign:96 https://mirrors.ustc.edu.cn/ubuntu focal-updates/restricted armhf Packages', 'Ign:107 https://mirrors.ustc.edu.cn/ubuntu focal-updates/universe armhf Packages', 'Ign:114 https://mirrors.ustc.edu.cn/ubuntu focal-updates/multiverse armhf Packages', 'Ign:115 https://mirrors.ustc.edu.cn/ubuntu focal-backports/main armhf Packages', 'Ign:116 https://mirrors.ustc.edu.cn/ubuntu focal-backports/universe armhf Packages', 'Ign:6 https://mirrors.ustc.edu.cn/ubuntu focal/main armhf Packages', 'Ign:117 https://mirrors.ustc.edu.cn/ubuntu focal-security/main armhf Packages', 'Ign:118 https://mirrors.ustc.edu.cn/ubuntu focal-security/restricted armhf Packages', 'Ign:119 https://mirrors.ustc.edu.cn/ubuntu focal-security/universe armhf Packages', 'Ign:120 https://mirrors.ustc.edu.cn/ubuntu focal-security/multiverse armhf Packages', 'Ign:43 https://mirrors.ustc.edu.cn/ubuntu focal/restricted armhf Packages', 'Ign:49 https://mirrors.ustc.edu.cn/ubuntu focal/universe armhf Packages', 'Ign:82 https://mirrors.ustc.edu.cn/ubuntu focal/multiverse armhf Packages', 'Ign:91 https://mirrors.ustc.edu.cn/ubuntu focal-updates/main armhf Packages', 'Ign:96 https://mirrors.ustc.edu.cn/ubuntu focal-updates/restricted armhf Packages', 'Ign:107 https://mirrors.ustc.edu.cn/ubuntu focal-updates/universe armhf Packages', 'Ign:114 https://mirrors.ustc.edu.cn/ubuntu focal-updates/multiverse armhf Packages', 'Ign:115 https://mirrors.ustc.edu.cn/ubuntu focal-backports/main armhf Packages', 'Ign:116 https://mirrors.ustc.edu.cn/ubuntu focal-backports/universe armhf Packages', 'Ign:6 https://mirrors.ustc.edu.cn/ubuntu focal/main armhf Packages', 'Ign:117 https://mirrors.ustc.edu.cn/ubuntu focal-security/main armhf Packages', 'Ign:118 https://mirrors.ustc.edu.cn/ubuntu focal-security/restricted armhf Packages', 'Ign:119 https://mirrors.ustc.edu.cn/ubuntu focal-security/universe armhf Packages', 'Ign:120 https://mirrors.ustc.edu.cn/ubuntu focal-security/multiverse armhf Packages', 'Ign:43 https://mirrors.ustc.edu.cn/ubuntu focal/restricted armhf Packages', 'Ign:49 https://mirrors.ustc.edu.cn/ubuntu focal/universe armhf Packages', 'Ign:82 https://mirrors.ustc.edu.cn/ubuntu focal/multiverse armhf Packages', 'Ign:91 https://mirrors.ustc.edu.cn/ubuntu focal-updates/main armhf Packages', 'Ign:96 https://mirrors.ustc.edu.cn/ubuntu focal-updates/restricted armhf Packages', 'Ign:107 https://mirrors.ustc.edu.cn/ubuntu focal-updates/universe armhf Packages', 'Ign:114 https://mirrors.ustc.edu.cn/ubuntu focal-updates/multiverse armhf Packages', 'Ign:115 https://mirrors.ustc.edu.cn/ubuntu focal-backports/main armhf Packages', 'Ign:116 https://mirrors.ustc.edu.cn/ubuntu focal-backports/universe armhf Packages', 'Ign:6 https://mirrors.ustc.edu.cn/ubuntu focal/main armhf Packages', 'Ign:117 https://mirrors.ustc.edu.cn/ubuntu focal-security/main armhf Packages', 'Ign:118 https://mirrors.ustc.edu.cn/ubuntu focal-security/restricted armhf Packages', 'Ign:119 https://mirrors.ustc.edu.cn/ubuntu focal-security/universe armhf Packages', 'Ign:120 https://mirrors.ustc.edu.cn/ubuntu focal-security/multiverse armhf Packages', 'Ign:43 https://mirrors.ustc.edu.cn/ubuntu focal/restricted armhf Packages', 'Ign:49 https://mirrors.ustc.edu.cn/ubuntu focal/universe armhf Packages', 'Ign:82 https://mirrors.ustc.edu.cn/ubuntu focal/multiverse armhf Packages', 'Ign:91 https://mirrors.ustc.edu.cn/ubuntu focal-updates/main armhf Packages', 'Ign:96 https://mirrors.ustc.edu.cn/ubuntu focal-updates/restricted armhf Packages', 'Ign:107 https://mirrors.ustc.edu.cn/ubuntu focal-updates/universe armhf Packages', 'Ign:114 https://mirrors.ustc.edu.cn/ubuntu focal-updates/multiverse armhf Packages', 'Ign:115 https://mirrors.ustc.edu.cn/ubuntu focal-backports/main armhf Packages', 'Ign:116 https://mirrors.ustc.edu.cn/ubuntu focal-backports/universe armhf Packages', 'Err:6 https://mirrors.ustc.edu.cn/ubuntu focal/main armhf Packages', '  404  Not Found [IP: 202.141.160.110 443]', 'Ign:117 https://mirrors.ustc.edu.cn/ubuntu focal-security/main armhf Packages', 'Ign:118 https://mirrors.ustc.edu.cn/ubuntu focal-security/restricted armhf Packages', 'Ign:119 https://mirrors.ustc.edu.cn/ubuntu focal-security/universe armhf Packages', 'Ign:120 https://mirrors.ustc.edu.cn/ubuntu focal-security/multiverse armhf Packages', 'Ign:43 https://mirrors.ustc.edu.cn/ubuntu focal/restricted armhf Packages', 'Ign:49 https://mirrors.ustc.edu.cn/ubuntu focal/universe armhf Packages', 'Ign:82 https://mirrors.ustc.edu.cn/ubuntu focal/multiverse armhf Packages', 'Err:91 https://mirrors.ustc.edu.cn/ubuntu focal-updates/main armhf Packages', '  404  Not Found [IP: 202.141.160.110 443]', 'Ign:96 https://mirrors.ustc.edu.cn/ubuntu focal-updates/restricted armhf Packages', 'Ign:107 https://mirrors.ustc.edu.cn/ubuntu focal-updates/universe armhf Packages', 'Ign:114 https://mirrors.ustc.edu.cn/ubuntu focal-updates/multiverse armhf Packages', 'Err:115 https://mirrors.ustc.edu.cn/ubuntu focal-backports/main armhf Packages', '  404  Not Found [IP: 202.141.160.110 443]', 'Ign:116 https://mirrors.ustc.edu.cn/ubuntu focal-backports/universe armhf Packages', 'Err:117 https://mirrors.ustc.edu.cn/ubuntu focal-security/main armhf Packages', '  404  Not Found [IP: 202.141.160.110 443]', 'Ign:118 https://mirrors.ustc.edu.cn/ubuntu focal-security/restricted armhf Packages', 'Ign:119 https://mirrors.ustc.edu.cn/ubuntu focal-security/universe armhf Packages', 'Ign:120 https://mirrors.ustc.edu.cn/ubuntu focal-security/multiverse armhf Packages', 'Reading package lists...', ''],['\n', 'WARNING: apt does not have a stable CLI interface. Use with caution in scripts.\n', '\n', 'E: Failed to fetch https://mirrors.ustc.edu.cn/ubuntu/dists/focal/main/binary-armhf/Packages  404  Not Found [IP: 202.141.160.110 443]\n', 'E: Failed to fetch https://mirrors.ustc.edu.cn/ubuntu/dists/focal-updates/main/binary-armhf/Packages  404  Not Found [IP: 202.141.160.110 443]\n', 'E: Failed to fetch https://mirrors.ustc.edu.cn/ubuntu/dists/focal-backports/main/binary-armhf/Packages  404  Not Found [IP: 202.141.160.110 443]\n', 'E: Failed to fetch https://mirrors.ustc.edu.cn/ubuntu/dists/focal-security/main/binary-armhf/Packages  404  Not Found [IP: 202.141.160.110 443]\n', 'E: Some index files failed to download. They have been ignored, or old ones used instead.\n']

**Comment by fishros** [comment]
请提供如下信息：
1.你的系统版本
2.你的系统架构
3.你的操作的上下文
4.其他有关于该问题的详细信息

**Comment by Geaso** [comment]
您好我也在使用一键安装时遇到了同样的问题想请教一下如何解决，是在树莓派4B上操作
系统：debian10.11：buster
架构：armhf
下文为使用网站一键安装后选择操作1【安装ros】的内容
有劳您了
小鱼:检测当前系统debian10.11:buster 支持一键安装ROS
RUN Choose Task:[请输入括号内的数字]
如果您是第一次安装，推荐您先更换一下系统源
[1]:更换系统源再继续安装
[2]:不更换继续安装
[0]:quit
请输入[]内的数字以选择:1
欢迎使用模板工程,本工具由作者小鱼提供
欢迎使用一键换源工具，本工具由[鱼香ROS]小鱼贡献..
RUN Choose Task:[请输入括号内的数字]
请选择换源方式
[1]:仅更换系统源
[2]:更换系统源并清理第三方源
[0]:quit
请输入[]内的数字以选择:1
Run CMD Task:[sudo rm -rf /etc/apt/sources.list]
[-]Result:success                           

Run CMD Task:[dpkg --print-architecture]
[-]Result:success                           

检测到当前系统架构为[armhf],正在为你更换对应源..
替换完成，尝试第一次更新....
Run CMD Task:[sudo apt update]
[-]Result:code:100                           ports buster-security Releaseeee

镜像修复完成.....
若遇到问题,可在github:https://github.com/fishros/提出issue反馈
Run CMD Task:[sudo apt update]
[-]Result:code:100                           ports buster-security Releaseeee

你的系统当前apt存在问题，请先使用一键换源处理...若无法处理，请将下列错误信息告知小鱼...['忽略:1 https://mirrors.ustc.edu.cn/ubuntu-ports buster InRelease', '忽略:2 https://mirrors.ustc.edu.cn/ubuntu-ports buster-updates InRelease', '忽略:3 https://mirrors.ustc.edu.cn/ubuntu-ports buster-backports InRelease', '忽略:4 https://mirrors.ustc.edu.cn/ubuntu-ports buster-security InRelease', '错误:5 https://mirrors.ustc.edu.cn/ubuntu-ports buster Release', '  404  Not Found [IP: 202.141.176.110 443]', '错误:6 https://mirrors.ustc.edu.cn/ubuntu-ports buster-updates Release', '  404  Not Found [IP: 202.141.176.110 443]', '错误:7 https://mirrors.ustc.edu.cn/ubuntu-ports buster-backports Release', '  404  Not Found [IP: 202.141.176.110 443]', '错误:8 https://mirrors.ustc.edu.cn/ubuntu-ports buster-security Release', '  404  Not Found [IP: 202.141.176.110 443]', '正在读取软件包列表...', ''],['\n', 'WARNING: apt does not have a stable CLI interface. Use with caution in scripts.\n', '\n', 'E: 仓库 “https://mirrors.ustc.edu.cn/ubuntu-ports buster Release” 没有 Release 文件。\n', 'E: 仓库 “https://mirrors.ustc.edu.cn/ubuntu-ports buster-updates Release” 没有 Release 文件。\n', 'E: 仓库 “https://mirrors.ustc.edu.cn/ubuntu-ports buster-backports Release” 没有 Release 文件。\n', 'E: 仓库 “https://mirrors.ustc.edu.cn/ubuntu-ports buster-security Release” 没有 Release 文件。\n']

**Comment by fishros** [comment]
问题是你所使用的系统和架构目前科大源（https://mirrors.ustc.edu.cn/ubuntu-ports/dists/）不支持造成，你可以更换ubuntu系统或者方便提供一个支持armhf+debian:buster的源，我来一键换源增加对该系统的支持。

**Comment by Geaso** [comment]
> 问题是你所使用的系统和架构目前科大源（ https://mirrors.ustc.edu.cn/ubuntu-ports/dists/ ）不支持造成，你可以更换ubuntu系统或者方便提供一个支持armhf+debian:buster的源，我来一键换源增加对该系统的支持。

感谢作者，考量了一下还是决定安装ubuntu来使用您的一键安装了，感谢您的帮助。

**Comment by fishros** [comment]
没问题，那我先把这个issue关闭了，如其他小伙伴遇到在debian的支持上的问题，可以提出新的issue。
