### ISSUE TITLE
sudo apt update一直报错：无法验证下列签名： NO_PUBKEY F42ED6FBAB17C654

### ISSUE THREAD

**Issue by 1129267324** [fishros/install#6]
![2022-03-10 10-38-25 的屏幕截图](https://user-images.githubusercontent.com/32668550/157577492-1bad8739-695f-4cc0-af6c-d67faf0fb94b.png)

**Comment by fishros** [comment]
看到报的错误你应该是手动添加了paclages.ros.org ros2的源，你可以删掉该源，然后通过一键安装ROS跑一遍即可。

**Comment by fishros** [comment]
如果没有后续反馈，我先将该问题关闭啦，有其他问题可以再提出~
