### ISSUE TITLE
在ubuntu22.04中使用docker安装ros1-noetic报错

### ISSUE THREAD

**Issue by xuzhibao** [fishros/install#64]
欢迎使用一键安装ROS-Docker版,支持所有版本ROS,本工具由作者小鱼提供
================================1.版本选择======================================
RUN Choose Task:[请输入括号内的数字]
请选择你要安装的ROS版本名称(请注意ROS1和ROS2区别):
[1]:jazzy    ROS2
[2]:noetic    ROS1
[3]:humble    ROS2
[4]:foxy    ROS2
[5]:galactic    ROS2
[6]:iron    ROS2
[7]:melodic    ROS1
[8]:rolling    ROS2
[9]:kinetic    ROS1
[10]:eloquent    ROS2
[11]:dashing    ROS2
[12]:crystal    ROS2
[13]:bouncy    ROS2
[14]:ardent    ROS2
[15]:lunar    ROS2
[16]:indigo    ROS1
[0]:quit
请输入[]内的数字以选择:2
你选择了None
================================2.安装Docker======================================
Run CMD Task:[docker version]
[-]Result:success                           76a6b735f29cc25774e

=================3.下载镜像（该步骤因网络原因会慢一些，若失败请重试）==================
Run CMD Task:[sudo docker pull None ]
invalid reference format: repository name (library/None) must be lowercase
Run CMD Task:[sudo docker pull None ]
invalid reference format: repository name (library/None) must be lowercase
Run CMD Task:[sudo docker pull None ]
invalid reference format: repository name (library/None) must be lowercase
================================4.生成容器======================================
请为你的noetic    ROS1容器取个名字吧！
>>ros1
收到名字ros1
Run CMD Task:[users]
[-]Result:success                           

Run CMD Task:[sudo docker run -dit --name=ros1 -v /home/bao:/home/bao -v /tmp/.X11-unix:/tmp/.X11-unix --device=/dev/dri/renderD128 -v /dev/dri:/dev/dri --device=/dev/snd -e DISPLAY=unix$DISPLAY -w /home/bao  None]
docker: invalid reference format: repository name (library/None) must be lowercase.
See 'docker run --help'.
Run CMD Task:[docker exec -it ros1 /bin/bash -c "echo -e '
source /opt/ros/noetic    ROS1/setup.bash' >> ~/.bashrc" ]
Error response from daemon: No such container: ros1
Run CMD Task:[xhost +local:]
non-network local connections being added to access control list
================================5.生成命令======================================
Traceback (most recent call last):
  File "/tmp/fishinstall/install.py", line 124, in <module>
    main()
  File "/tmp/fishinstall/install.py", line 116, in main
    run_tool_file(tools[code]['tool'].replace(url_prefix,'').replace("/","."))
  File "/tmp/fishinstall/tools/base.py", line 1297, in run_tool_file
    if tool.run()==False: return False
  File "/tmp/fishinstall/tools/tool_install_ros_with_docker.py", line 249, in run
    self.install_ros_with_docker()
  File "/tmp/fishinstall/tools/tool_install_ros_with_docker.py", line 238, in install_ros_with_docker
    self.generte_command(container_name,rosname)
  File "/tmp/fishinstall/tools/tool_install_ros_with_docker.py", line 199, in generte_command
    rosversion = RosVersions.get_ros_version(rosname).version
AttributeError: 'NoneType' object has no attribute 'version'

**Comment by Hawking-z** [comment]
我也出现这个问题，看了源码发现是代码出现bug了，为了显示ROS版本导致后面的判断出错。这个要么找作者修改，要么就自己把代码下下来修改运行就可以解决了

**Comment by AngryTurtle2** [comment]
Sorry
我测试时，没出现这个报错。不好意思。我找时间改一改。应该问题不大。
@xuzhibao @Hawking-z

**Comment by AngryTurtle2** [comment]
Sorry
我测试时，没出现这个报错。不好意思。我找时间改一改。应该问题不大。
@xuzhibao @Hawking-z

**Comment by AngryTurtle2** [comment]
你好
@xuzhibao @Hawking-z
已经提交了新的PR。等待合并中。
感谢你们的付出。欢迎你们来继续测试这个安装docker版的脚本。
同时也非常抱歉由于我测试的不严谨，导致了各位的麻烦。
真的非常抱歉。
提交的PR在这里。
[修复PR#59的bug #65](https://github.com/fishros/install/pull/65)

**Comment by fishros** [comment]
已合并~
