### ISSUE TITLE
NVIDIA 驱动 + ROS in Docker + RViz => 不能启动

### ISSUE THREAD

**Issue by 14725** [fishros/install#67]
在电脑使用 NVIDIA 驱动，使用一键安装安装 Docker 版的 ROS 后，无法在容器中启动 Gazebo 和 RViz …… （但是提示我给忘了……）

希望给个修复（）

某使用 Docker 的另外的项目遇到了同样的问题并且有缓解方法 https://github.com/huan/docker-wechat/issues/50 …… ，在我自己的电脑上面有效。

Ubuntu 22.10. Driver Version: 535.183.01

**Comment by fishros** [comment]
nvidia需要专门的docker镜像才行
