### ISSUE TITLE
Ubuntu18.04 安装 docker版微信 只能启动一次

### ISSUE THREAD

**Issue by Roger-Sh** [fishros/install#69]
鱼香大佬，你好，

我在尝试Ubuntu18.04 安装 docker版微信后，发现每次微信只能启动一次，关闭后运行 wechat 指令后输入 s 不会再有任何反应，除非电脑重启。请问你有遇到过类似的问题吗？

另外，每次启动微信后，wine 的图标也会出现在图标栏，甚至还会出现两个，请问有什么方法可以隐藏 wine 的图标吗

**Comment by fishros** [comment]
试试 restart
