### ISSUE TITLE
如何卸载?

### ISSUE THREAD

**Issue by Irvingao** [fishros/install#7]
我安装了ROS后出现了很多软件的依赖问题，我想完全卸载，请问如何操作呢?

**Comment by fishros** [comment]
可以尝试使用[aptitude工具](https://github.com/fishros/install/issues/5#issuecomment-1046560257)解决依赖问题，进行手动安装和卸载。

**Comment by Irvingao** [comment]
我现在ROS都卸不掉了，用aptitude。

**Comment by fishros** [comment]
> 我现在ROS都卸不掉了，用aptitude。

你好，请给出对判断错误有用的信息，比如：
- 系统版本
- 系统环境
- ROS版本
- 错误信息
- 上下文操作
- 你的其他尝试及结果
- 其他可以方便定位的信息等

如果你直接说卸载不掉，我也无法为你提供帮助。

另外一个小提示，第一次安装提示换源时，一定要更换，用默认的系统源很容易安装不全造成依赖问题。
