### ISSUE TITLE
AttributeError: module 'tools.tool_install_ros' has no attribute 'Tool'

### ISSUE THREAD

**Issue by RuiHuangNUS** [fishros/install#73]
Type the number in [] to choose a function:1
Run CMD Task:[wget http://mirror.fishros.com/install/tools/tool_install_ros.py -O /tmp/fishinstall/tools/tool_install_ros.py --no-check-certificate]
[/][1.60s] --2024-09-04 21:27:23--  http://mirror.fishros.com/install/tools/tool[\][1.61s] 正在解析主机 mirror.fishros.com (mirror.fishros.com)... 47.119.165.16[|][1.61s] 正在连接 mirror.fishros.com (mirror.fishros.com)|47.119.165.169|:80..[-][1.61s] CMD Result:code:8                                                

Run CMD Task:[wget http://mirror.fishros.com/install/tools/tool_config_rosenv.py -O /tmp/fishinstall/tools/tool_config_rosenv.py --no-check-certificate]
[/][3.41s] --2024-09-04 21:27:25--  http://mirror.fishros.com/install/tools/tool[\][3.49s] 正在解析主机 mirror.fishros.com (mirror.fishros.com)... 47.119.165.16[|][3.49s] 正在连接 mirror.fishros.com (mirror.fishros.com)|47.119.165.169|:80..[-][3.49s] CMD Result:success                                               

Run CMD Task:[wget http://mirror.fishros.com/install/tools/tool_config_system_source.py -O /tmp/fishinstall/tools/tool_config_system_source.py --no-check-certificate]
[/][0.50s] --2024-09-04 21:27:28--  http://mirror.fishros.com/install/tools/tool[\][0.59s] 正在解析主机 mirror.fishros.com (mirror.fishros.com)... 47.119.165.16[|][0.59s] 正在连接 mirror.fishros.com (mirror.fishros.com)|47.119.165.169|:80..[-][0.59s] CMD Result:success                                               

Traceback (most recent call last):
  File "/tmp/fishinstall/install.py", line 125, in <module>
    main()
  File "/tmp/fishinstall/install.py", line 117, in main
    run_tool_file(tools[code]['tool'].replace(url_prefix,'').replace("/","."))
  File "/tmp/fishinstall/tools/base.py", line 1408, in run_tool_file
    tool = importlib.import_module(file.replace(".py","")).Tool()
AttributeError: module 'tools.tool_install_ros' has no attribute 'Tool'

**Comment by fishros** [comment]
尝试重新运行下试试，偶然的下载失败应该

**Comment by RuiHuangNUS** [comment]
我在境外，这几天都不行。之前还成功过。

**Comment by fishros** [comment]
这个网址触发关键词了估计，我给你提供一个新的命令

sudo apt install git -y && git clone https://github.com/fishros/install.git && cd install && sudo python3 install.py

**Comment by RuiHuangNUS** [comment]
Traceback (most recent call last):
  File "install.py", line 125, in <module>
    main()
  File "install.py", line 117, in main
    run_tool_file(tools[code]['tool'].replace(url_prefix,'').replace("/","."))
  File "/home/ruihuang/install/tools/base.py", line 1408, in run_tool_file
    tool = importlib.import_module(file.replace(".py","")).Tool()
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'toolstool_install_ros'

**Comment by fishros** [comment]
正在修复

**Comment by fishros** [comment]
已经修复,请尝试

rm -rf install && sudo apt install git -y && git clone https://github.com/fishros/install.git && cd install && sudo python3 install.py

**Comment by RuiHuangNUS** [comment]
成功了，感谢！
