### ISSUE TITLE
一键安装ros在选择仅换源后出现报错

### ISSUE THREAD

**Issue by homohifi** [fishros/install#8]
你的系统当前apt存在问题，请先使用一键换源处理...若无法处理，请将下列错误信息告知小鱼...,['\n', 'WARNING: apt does not have a stable CLI interface. Use with caution in scripts.\n', '\n', 'E: 仓库 “https://mirrors.ustc.edu.cn/ubuntu-ports buster Release” 没有 Release 文件。\n', 'E: 仓库 “https://mirrors.ustc.edu.cn/ubuntu-ports buster-updates Release” 没有 Release 文件。\n', 'E: 仓库 “https://mirrors.ustc.edu.cn/ubuntu-ports buster-backports Release” 没有 Release 文件。\n', 'E: 仓库 “https://mirrors.ustc.edu.cn/ubuntu-ports buster-security Release” 没有 Release 文件。\n']

**Comment by fishros** [comment]
请到鱼香社区反馈：https://fishros.org.cn/forum/category/7/%E4%B8%80%E9%94%AE%E5%AE%89%E8%A3%85
![image](https://user-images.githubusercontent.com/87068644/160118995-e8d916a0-ac7e-40c0-9821-27d326c67ade.png)
